version: '2'
services:

  master:
    image: ${MYSQL_IMAGE}:${MYSQL_TAG}
    container_name: orchestrator_${COMPOSE_PROJECT_NAME}_master
    hostname: orchestrator_${COMPOSE_PROJECT_NAME}_master
    networks:
      orch_network:
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./cnf_files/my.cnf.master:/etc/my.cnf

  slave01:
    image: ${MYSQL_IMAGE}:${MYSQL_TAG}
    container_name: orchestrator_${COMPOSE_PROJECT_NAME}_slave01
    hostname: orchestrator_${COMPOSE_PROJECT_NAME}_slave01
    networks:
      orch_network:
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - master
    volumes:
      - ./cnf_files/my.cnf.slave01:/etc/my.cnf

  slave02:
    image: ${MYSQL_IMAGE}:${MYSQL_TAG}
    container_name: orchestrator_${COMPOSE_PROJECT_NAME}_slave02
    hostname: orchestrator_${COMPOSE_PROJECT_NAME}_slave02
    networks:
      orch_network:
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - master
    volumes:
      - ./cnf_files/my.cnf.slave02:/etc/my.cnf

  orchestrator01:
    image: ${ORCHESTRATOR_IMAGE}:${ORCHESTRATOR_TAG}
    container_name: orchestrator_${COMPOSE_PROJECT_NAME}_orchestrator01
    hostname: orchestrator_${COMPOSE_PROJECT_NAME}_orchestrator_1
    networks:
      orch_network:
    ports:
      - 3000
    depends_on:
      - slave02
    volumes:
      - ./cnf_files/orchestrator_1.cnf:/etc/orchestrator.conf.json

  orchestrator02:
    image: ${ORCHESTRATOR_IMAGE}:${ORCHESTRATOR_TAG}
    container_name: orchestrator_${COMPOSE_PROJECT_NAME}_orchestrator02
    hostname: orchestrator_${COMPOSE_PROJECT_NAME}_orchestrator_2
    networks:
      orch_network:
    ports:
      - 3000
    depends_on:
      - slave02
    volumes:
      - ./cnf_files/orchestrator_2.cnf:/etc/orchestrator.conf.json

  orchestrator03:
    image: ${ORCHESTRATOR_IMAGE}:${ORCHESTRATOR_TAG}
    container_name: orchestrator_${COMPOSE_PROJECT_NAME}_orchestrator03
    hostname: orchestrator_${COMPOSE_PROJECT_NAME}_orchestrator_3
    networks:
      orch_network:
    ports:
      - 3000
    depends_on:
      - slave02
    volumes:
      - ./cnf_files/orchestrator_3.cnf:/etc/orchestrator.conf.json

networks:
  orch_network:
    driver: bridge

